// {
//     "FpGNaqOBahOAM1ETCCwkMzGYlfu2":{
//       "001": {
//         "name": "Street Fighter 6",
//         "src": "sf6.jpg",
//         "genre1": "Файтинг",
//         "genre2": "Приключения",
//         "genre3": "РПГ",
//         "genres": "Файтинг, Приключения, РПГ",
//         "oldprice": "9999",
//         "price": "5299",
//         "collection": "",
//         "popular": "true",
//         "style": "rec",
//         "availability": "true"
//       },
//       "002": {
//         "name": "Watch Dogs: Legion",
//         "src": "wd.png",
//         "genre1": "Экшен",
//         "genre2": "Шутер",
//         "genre3": "Приключения",
//         "genres": "Экшен, Шутер, Приключения",
//         "oldprice": "9999",
//         "price": "1679",
//         "collection": "Сильный сюжет",
//         "popular": "true",
//         "style": "top",
//         "availability": "true"
//       },
//     }
// }
