// {
//     "games": {
//       "001": {
//         "name": "Street Fighter 6",
//         "src": "sf6.jpg",
//         "genre1": "Файтинг",
//         "genre2": "Приключения",
//         "genre3": "РПГ",
//         "genres": "Файтинг, Приключения, РПГ",
//         "oldprice": "9999",
//         "price": "5299",
//         "collection": "",
//         "popular": "true",
//         "style": "rec",
//         "availability": "true"
//       },
//       "002": {
//         "name": "Watch Dogs: Legion",
//         "src": "wd.png",
//         "genre1": "Экшен",
//         "genre2": "Шутер",
//         "genre3": "Приключения",
//         "genres": "Экшен, Шутер, Приключения",
//         "oldprice": "9999",
//         "price": "1679",
//         "collection": "Сильный сюжет",
//         "popular": "true",
//         "style": "top",
//         "availability": "true"
//       },
//       "003": {
//         "name": "Far Cry 6",
//         "src": "farcry.png",
//         "genre1": "Экшен",
//         "genre2": "Шутер",
//         "genre3": "РПГ",
//         "genres": "Экшен, Шутер, РПГ",
//         "oldprice": "9999",
//         "price": "1899",
//         "collection": "Сильный сюжет",
//         "popular": "true",
//         "style": "top",
//         "availability": "true"
//       },
//       "004": {
//         "name": "Resident Evil 7",
//         "src": "residentevil.jpg",
//         "genre1": "Хоррор",
//         "genre2": "Шутер",
//         "genre3": "Приключения",
//         "genres": "Хоррор, Шутер, Приключения",
//         "oldprice": "9999",
//         "price": "999",
//         "collection": "Сильный сюжет",
//         "popular": "true",
//         "style": "rec",
//         "availability": "true"
//       },
//       "005": {
//         "name": "Pacific Drive",
//         "src": "pd.jpg",
//         "genre1": "Инди",
//         "genre2": "Симулятор",
//         "genre3": "Приключения",
//         "genres": "Инди, Симулятор, Приключения",
//         "oldprice": "9999",
//         "price": "2289",
//         "collection": "Веселье",
//         "popular": "true",
//         "style": "new",
//         "availability": "true"
//       },
//       "006": {
//         "name": "Days Gone",
//         "src": "dg.png",
//         "genre1": "Шутер",
//         "genre2": "Хоррор",
//         "genre3": "Приключения",
//         "genres": "Шутер, Хоррор, Приключения",
//         "oldprice": "9999",
//         "price": "1679",
//         "collection": "Открытый мир",
//         "popular": "true",
//         "style": "new",
//         "availability": "false"
//       },
//       "007": {
//         "name": "Red Dead Redemption 2",
//         "src": "rdr.png",
//         "genre1": "Шутер",
//         "genre2": "Экшен",
//         "genre3": "Приключения",
//         "genres": "Шутер, Экшен, Приключения",
//         "oldprice": "9999",
//         "price": "2859",
//         "collection": "Открытый мир",
//         "popular": "true",
//         "style": "rec",
//         "availability": "true"
//       },
//       "008": {
//         "name": "UFC 5",
//         "src": "ufc.jpg",
//         "genre1": "Файтинг",
//         "genre2": "Экшен",
//         "genre3": "Шутер",
//         "genres": "Файтинг, Экшен, Шутер",
//         "oldprice": "9999",
//         "price": "2859",
//         "collection": "Веселье",
//         "popular": "false",
//         "style": "rec",
//         "availability": "true"
//       },
//       "009": {
//         "name": "Cyberpunk 2077",
//         "src": "cyber.jpg",
//         "genre1": "Шутер",
//         "genre2": "Приключения",
//         "genre3": "Файтинг",
//         "genres": "Шутер, Приключения, Файтинг",
//         "oldprice": "9999",
//         "price": "3919",
//         "collection": "Сильный сюжет",
//         "popular": "false",
//         "style": "top",
//         "availability": "true"
//       },
//       "010": {
//         "name": "Critter Crops",
//         "src": "crcr.jpg",
//         "genre1": "Шутер",
//         "genre2": "Приключения",
//         "genre3": "Файтинг",
//         "genres": "Шутер, Приключения, Файтинг",
//         "oldprice": "1599",
//         "price": "1899",
//         "collection": "Сильный сюжет",
//         "popular": "false",
//         "style": "new",
//         "availability": "false"
//       },
//       "011": {
//         "name": "Cataclismo",
//         "src": "catac.jpg",
//         "genre1": "Шутер",
//         "genre2": "Приключения",
//         "genre3": "Файтинг",
//         "genres": "Шутер, Приключения, Файтинг",
//         "oldprice": "1299",
//         "price": "1599",
//         "collection": "Сильный сюжет",
//         "popular": "false",
//         "style": "sale",
//         "availability": "false"
//       },
//       "012": {
//         "name": "Sand Walkers",
//         "src": "sw.jpg",
//         "genre1": "Шутер",
//         "genre2": "Приключения",
//         "genre3": "Файтинг",
//         "genres": "Шутер, Приключения, Файтинг",
//         "oldprice": "1099",
//         "price": "1199",
//         "collection": "Веселье",
//         "popular": "false",
//         "style": "sale",
//         "availability": "false"
//       },
//       "013": {
//         "name": "Need for Speed: Heat",
//         "src": "nfs.jpg",
//         "genre1": "Шутер",
//         "genre2": "Приключения",
//         "genre3": "Файтинг",
//         "genres": "Шутер, Приключения, Файтинг",
//         "oldprice": "1849",
//         "price": "2499",
//         "collection": "Веселье",
//         "popular": "false",
//         "style": "sale",
//         "availability": "true"
//       }
//     }

//   }
