export const popularGames = [
  {
    name: "Watch Dogs: Legion",
    src: "wd.png",
    genre1: "Экшен",
    genre2: "Шутер",
    genre3: "Приключения",
    price: "1679",
  },
  {
    name: "Far Cry 6",
    src: "farcry.png",
    genre1: "Экшен",
    genre2: "Шутер",
    genre3: "РПГ",
    price: "1899",
  },
  {
    name: "Resident Evil 7",
    src: "residentevil.jpg",
    genre1: "Хоррор",
    genre2: "Шутер",
    genre3: "Приключения",
    price: "999",
  },
  {
    name: "Street Fighter 6",
    src: "sf6.jpg",
    genre1: "Файтинг",
    genre2: "Приключения",
    genre3: "РПГ",
    price: "5299",
  },
  {
    name: "Pacific Drive",
    src: "pd.jpg",
    genre1: "Инди",
    genre2: "Симулятор",
    genre3: "Приключения",
    price: "2289",
  },
  {
    name: "Days Gone",
    src: "dg.png",
    genre1: "Шутер",
    genre2: "Хоррор",
    genre3: "Приключения",
    price: "1679",
  },
  {
    name: "Red Dead Redemption 2",
    src: "rdr.png",
    genre1: "Шутер",
    genre2: "Экшен",
    genre3: "Приключения",
    price: "2859",
  },
  {
    name: "UFC 5",
    src: "ufc.jpg",
    genre1: "Файтинг",
    genre2: "Экшен",
    genre3: "Шутер",
    price: "2859",
  },
  {
    name: "Cyberpunk 2077",
    src: "cyber.jpg",
    genre1: "Шутер",
    genre2: "Приключения",
    genre3: "Файтинг",
    price: "3919",
  },
];
